import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';

export interface Contract {
  id: string;
  contract_number: string;
  contract_type: 'venda' | 'compra';
  status: 'draft' | 'pending' | 'signed' | 'cancelled';
  customer_id?: string;
  customer_name: string;
  customer_nationality?: string;
  customer_profession?: string;
  customer_marital_status?: string;
  customer_rg?: string;
  customer_cpf?: string;
  customer_birth_date?: string;
  customer_address?: string;
  customer_city?: string;
  customer_state?: string;
  customer_zip?: string;
  customer_phone?: string;
  customer_email?: string;
  vehicle_id?: string;
  vehicle_brand: string;
  vehicle_model: string;
  vehicle_year: string;
  vehicle_plate?: string;
  vehicle_color?: string;
  vehicle_renavam?: string;
  vehicle_odometer?: number;
  vehicle_value: number;
  trade_in_brand?: string;
  trade_in_model?: string;
  trade_in_year?: string;
  trade_in_plate?: string;
  trade_in_color?: string;
  trade_in_renavam?: string;
  trade_in_value?: number;
  down_payment?: number;
  installments_count?: number;
  installment_value?: number;
  installment_due_day?: number;
  notes?: string;
  signed_at?: string;
  created_by?: string;
  created_at: string;
  updated_at: string;
}

export interface ContractFormData {
  contract_type: 'venda' | 'compra';
  customer_id?: string;
  customer_name: string;
  customer_nationality?: string;
  customer_profession?: string;
  customer_marital_status?: string;
  customer_rg?: string;
  customer_cpf?: string;
  customer_birth_date?: string;
  customer_address?: string;
  customer_city?: string;
  customer_state?: string;
  customer_zip?: string;
  customer_phone?: string;
  customer_email?: string;
  vehicle_id?: string;
  vehicle_brand: string;
  vehicle_model: string;
  vehicle_year: string;
  vehicle_plate?: string;
  vehicle_color?: string;
  vehicle_renavam?: string;
  vehicle_odometer?: number;
  vehicle_value: number;
  trade_in_brand?: string;
  trade_in_model?: string;
  trade_in_year?: string;
  trade_in_plate?: string;
  trade_in_color?: string;
  trade_in_renavam?: string;
  trade_in_value?: number;
  down_payment?: number;
  installments_count?: number;
  installment_value?: number;
  installment_due_day?: number;
  negotiation_details?: string; // Campo de negociação editável
  notes?: string;
}

export function useContracts() {
  const queryClient = useQueryClient();

  const { data: contracts = [], isLoading, error } = useQuery({
    queryKey: ['contracts'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('contracts')
        .select('*')
        .order('created_at', { ascending: false });
      
      if (error) throw error;
      return data as Contract[];
    },
  });

  const createContract = useMutation({
    mutationFn: async (data: ContractFormData & { updateRelated?: boolean }) => {
      const { updateRelated, negotiation_details, ...contractData } = data;
      
      // Se updateRelated = true, atualiza cliente e veículo com os dados do contrato
      if (updateRelated && contractData.customer_id) {
        await supabase
          .from('customers')
          .update({
            name: contractData.customer_name,
            cpf_cnpj: contractData.customer_cpf || null,
            rg: contractData.customer_rg || null,
            phone: contractData.customer_phone || null,
            email: contractData.customer_email || null,
            address: contractData.customer_address || null,
            city: contractData.customer_city || null,
            state: contractData.customer_state || null,
          })
          .eq('id', contractData.customer_id);
      }

      if (updateRelated && contractData.vehicle_id) {
        await supabase
          .from('vehicles')
          .update({
            plate: contractData.vehicle_plate || null,
            color: contractData.vehicle_color || null,
            renavam: contractData.vehicle_renavam || null,
            km: contractData.vehicle_odometer || null,
          })
          .eq('id', contractData.vehicle_id);
      }

      const { data: result, error } = await supabase
        .from('contracts')
        .insert({
          ...contractData,
          contract_number: '', // Will be auto-generated by trigger
        })
        .select()
        .single();
      
      if (error) throw error;
      return result;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['contracts'] });
      queryClient.invalidateQueries({ queryKey: ['customers'] });
      queryClient.invalidateQueries({ queryKey: ['vehicles'] });
      toast.success('Contrato criado com sucesso!');
    },
    onError: (error) => {
      console.error('Error creating contract:', error);
      toast.error('Erro ao criar contrato');
    },
  });

  const updateContract = useMutation({
    mutationFn: async ({ id, ...data }: Partial<Contract> & { id: string }) => {
      // Get current contract to check for status change
      const { data: currentContract } = await supabase
        .from('contracts')
        .select('*')
        .eq('id', id)
        .single();

      const { data: result, error } = await supabase
        .from('contracts')
        .update(data)
        .eq('id', id)
        .select()
        .single();
      
      if (error) throw error;

      // If contract was signed and has trade-in, notify managers
      if (data.status === 'signed' && currentContract?.status !== 'signed' && currentContract?.trade_in_brand) {
        // Get all managers
        const { data: managers } = await supabase
          .from('user_roles')
          .select('user_id')
          .eq('role', 'gerente');

        if (managers && managers.length > 0) {
          const notifications = managers.map(m => ({
            user_id: m.user_id,
            type: 'trade_in_pending',
            title: '🚗 Veículo de Troca para Cadastrar',
            message: `Contrato ${result.contract_number} assinado com veículo de troca: ${currentContract.trade_in_brand} ${currentContract.trade_in_model || ''}`,
            link: `/vendas/contratos?trade_in=${id}`,
          }));

          await supabase.from('notifications').insert(notifications);
        }
      }

      return result;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['contracts'] });
      toast.success('Contrato atualizado com sucesso!');
    },
    onError: (error) => {
      console.error('Error updating contract:', error);
      toast.error('Erro ao atualizar contrato');
    },
  });

  const deleteContract = useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from('contracts')
        .delete()
        .eq('id', id);
      
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['contracts'] });
      toast.success('Contrato excluído com sucesso!');
    },
    onError: (error) => {
      console.error('Error deleting contract:', error);
      toast.error('Erro ao excluir contrato');
    },
  });

  const stats = {
    total: contracts.length,
    signed: contracts.filter(c => c.status === 'signed').length,
    pending: contracts.filter(c => c.status === 'pending').length,
    draft: contracts.filter(c => c.status === 'draft').length,
  };

  return {
    contracts,
    isLoading,
    error,
    stats,
    createContract,
    updateContract,
    deleteContract,
  };
}
