// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahfoixzdnpswuqavbmgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoZm9peHpkbnBzd3VxYXZibWdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU2MDE0MTcsImV4cCI6MjA4MTE3NzQxN30.7n1o2ruVobI7EOFcSeYR_2NPdAhL3a7sALqFcf9Uzf0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Disable automatic session detection from URL to prevent re-renders on tab focus
    detectSessionInUrl: false,
  }
});